version: '3.8'
services:
  backend:
    build: ./backend
    container_name: backend
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://mongo:27017/mern-db
    depends_on:
      - mongo
    networks:
      - app-network



  frontend:
    build: ./frontend
    container_name: frontend
    environment:
      - PORT=3000
    networks:
      - app-network

  mongo:
    image: mongo
    container_name: mongo
    ports:
      - 27017:27017
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: nginx-load-balancer
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
